version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0

    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-base pandoc texlive-fonts-recommended
          rm pdf/* || true
          mkdir -p pdf

          for file in privacy terms designer-agreement partner-agreement; do
            pandoc $file.md -o pdf/$file.pdf
          done

          (cat partner-agreement.md && echo '\n---\n' && cat terms.md) | pandoc -o pdf/partner-agreement-and-terms.pdf
          (cat designer-agreement.md && echo '\n---\n' && cat terms.md) | pandoc -o pdf/designer-agreement-and-terms.pdf
      - deploy:
          name: Add built copies
          command: |
            git config --global user.email "devops@ca.la"
            git config --global user.name "CALA Machine User"

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git add pdf
              git commit -m '[ci skip] Add PDF copies'
              git push origin master
            fi
